import './App.css';
import Link from './components/Link';
import Card from './components/Card';
import Subt from './components/Subt';

function App() {
  return (
    <div className="App">
      <h1 className='title'>Notas biblicas de Sebas</h1>
      <Card title='Y sabemos que a los que aman a Dios, todas las cosas les ayudan a bien'>
        <Link text='Romanos 8:28' src='https://www.bible.com/bible/149/ROM.8.RVR1960' /> Amar el amor nos identifica, amarnos los unos a los otros <Link text='1 Corintios 13' src='https://www.bible.com/bible/127/1CO.13.NTV' /> El conocimiento se queda aqui mas no el amor. <br /> Enseñame a amar, no hay que dejar de amar, el se merece lo mejor de nosotros. Todo hacer con amor, dones, privilegios etc. Toleremos andar en amor, Deja el rencor Limpia esa mente, ese corazon. <br /> Desde el vientre se ama, no odies que es lo contrario del amor. <Link text='1 Pedro 2:17' src='https://www.bible.com/bible/127/1PE.2.NTV' /> <Link text='Galatas 6:10' src='https://www.bible.com/bible/127/GAL.6.NTV' /> Mayormente amar a la familia de la fe. <br /><Link text='Juan 13:34-35' src='https://www.bible.com/bible/127/JHN.13.NTV' /> Amar para demostrar que somos hijos de Dios. 
      </Card>
      
      <Card title='Un dia despues del bautismo'>
        <Link text='Mateo 3:13' src='https://www.bible.com/bible/127/MAT.3.NTV' /> Bautizo de Jesus, veamos que sucede despues del Bautizo <Link text='Mateo 4:1' src='https://www.bible.com/bible/127/MAT.4.NTV' />. <br /> Desierto = prueba, soledad, lugar para pastorear - <Link text='Numeros 14:33' />, Dios pastoreo a su pueblo. <br /> Cuando lo acabamos de recibir el nos cuida, por que no quiren que retrocedamos <Link text='Exodo 13:17' src='https://www.bible.com/bible/127/EXO.13.NTV' /> Pero cuando nos bautizamos vienen las pruebas <Link text='Exodo 15:22' src='https://www.bible.com/bible/127/EXO.15.NTV' /> Entraron a un desierto, Shur = pared, muro. Las pruebas son una pared. <br /> Arriesgamos nuestra vida al no obedecer, no hay que perdernos, <Link text='Jeremias 6:16' src='https://www.bible.com/bible/127/JER.6.NTV' /> Preguntar por el buen camino parar, reflexionar y retomar el buen camino, no desobedecer. <br /> El desierto es dolor es sufrimiento tambien en la vida espiritual, ahi somos pastoreados. Ahi tenemos que ver que dependemos de alguien para vivir porque en el desierto esta lleno de animales peligrosos tambien en el mundo espiritual, pero de todo eso nos cuida el señor. <br /> Nace de nuevo, vamos entra al desierto que ahi es donde se manifiesta el señor, sin pruebas no hay victoria por eso despues del bautizo hay pruebas. Los pensamientos se convierten en una muralla, tranquilo nostros todo lo podemos en Cristo que nos fortalece. <br /><Link text='Exodo 15:23' src='https://www.bible.com/bible/127/EXO.15.NTV' /> Aguas amargas, en este pasaje nos enseña a depender de el, como Moises clamo por agua en un desierto y Dios les respondio con un arbol que es tipo de Cristo para endulzar esas aguas amargas el nos enseña que es nuestro proveedor. Las aguas amargas eran para probarlos pero ellos murmuraron, no hacer eso confiar en él. <br /> Y recuerda que ellos murmuraron contra Moises pero en su escritura dice que contra Dios, cuando murmuramos con el que tenemos enfrente si es enviado de Dios contra el murmuramos, aunque no sea el pastor recordar que todos somos hijos de Dios todos tenemos a Dios en nuestros corazones.
      </Card>

      <Card title='El rio Éufrates' >
        <Link text='Genesis 2:10' src='https://www.bible.com/bible/127/GEN.2.NTV' /> Del rio de Edén se dividio en 4 brazos: <br /> 1. Pison, <Link text='Genesis 2:11' src='https://www.bible.com/bible/127/GEN.2.NTV' /> <br /> 2. Gihón, <Link text='Genesis 2:13' src='https://www.bible.com/bible/127/GEN.2.NTV' /> <br /> 3. Tigris, <Link text='Genesis 2:14' src='https://www.bible.com/bible/127/GEN.2.NTV' /> <br /> 4. Éufrates, <Link text='Genesis 2:14' src='https://www.bible.com/bible/127/GEN.2.NTV' /> <br /> Antes hablemos que existio un Edén antes que este del terrenal <Link text='Ezequiel 28:13' src='https://www.bible.com/bible/127/EZK.28.NTV' /> Mencionan que lucero se encontraba en ese jardin de Dios, la tierra fue creada a semejanza del cielo. <br /> Volvamos con los rios, Su inicio comenzo con la formacion del hombre/Edén y su final sera con el mismo final del hombre. <br /><Subt sub='Los cuatro angeles' /> En apocalipsis vuelve a aparecer el rio, <Link text='Apocalipsis 9:14' src='https://www.bible.com/bible/127/REV.9.NTV' /> Y en <Link text='Apocalipsis 16:12' src='https://www.bible.com/bible/127/REV.16.NTV' /> Ya se explica que ese rio se secara para que los reyes pasen por el para enfrentar a Israel. <br /> Copa tipo de juicio y dice que derramo su copa, en <Link text='Apocalipsis 9:14' src='https://www.bible.com/bible/127/REV.9.NTV' /> Se habla sobre los cuatro angel que seran desatados, primero si seran desatados quiere decir que son malos, la bilbia dice angeles pero en realidad son demonios, por eso seran desatados por que fueron vencidos. Cada imperio que se levanta tiene un principado, un rey, un angel. 
        <br /> En <Link text='Daniel 9:3' src='https://www.bible.com/bible/127/DAN.9.NTV' /> Daniel entro en luto, En <Link text='Daniel 10:2' src='https://www.bible.com/bible/127/DAN.10.NTV' /> se explica que por tres semanas estuvo de luto <Link text='Daniel 10:11-12' src='https://www.bible.com/bible/127/DAN.10.NTV' /> aqui ya se le presento un angel a Daniel y le dijo que desde el primer dia lo habia escuchado Jehova, podemos darnos cuenta que a nosotros tambien desde el primer dia nos escucha pero solo Dios sabe del por que no pasa las cosas en el momento que muchas veces queremos nostros. <br /> Tambien nos podemos dar cuenta que el dejo de estar en luto hasta que a la tercera semana el angel le hablo, podemos ver que estas personas se doblegaban hasta recibir una respuesta no solamente oraban una hora o un dia si no hasta recibir una respuesta, como el coro que dice "vamos orando hasta que baje el poder de Dios" realmente tenemos que orar todo el tiempo aunque todavia no se solucione o no recibamos lo que pidamos. <br /> Bueno pero volviendo con el angel, el lo enviaron desde el primer dia como dice Daniel pero en <Link text='Daniel 10:13' src='https://www.bible.com/bible/127/DAN.10.NTV' /> explica que se le opuso un rey, el rey de Persia, nos podemos dar cuenta de las grandes batallas que se desatan, con tan solo ir a la iglesia ya es una gran batalla que los hijos de Dios han ganado contra esas potestades de demonios. <br /> Volviendo con los 4 angeles aqui explica cuando fue vencido este rey, este angel uno de los 4 que se mencionan en Apocalipsis de que fueron desatados y por eso estos imperios ya no estan actualmente: <br /> 1. Persa <br /> 2. Babilonico <br /> 3. Romano <br /> 4. Griego <br /> 
        <Link text='Daniel 10:20' src='https://www.bible.com/bible/127/DAN.10.NTV' /> Aqui habla de que fue a vencer a otro rey el de Grecia y tambien habla sobre el angel que esta sobre Israel el angel Miguel, el rey de Israel <Link text='Daniel 12:1--' src='https://www.bible.com/bible/127/DAN.12.NTV' /> aqui podemos ver que este angel pelea por Israel <br /> Ya por ultimo en <Link text='Apocalipsis 9:15' src='https://www.bible.com/bible/127/REV.9.NTV' /> al tocar la sexta trompeta se levantaran estos reyes a matar y dice que su ejercito es de 200M son muchas personas y como dice mas adelante, con cabezas de leon, no esperemos eso si no algo mas a nuestra epoca y en <Link text='Apocalipsis 16:18' src='https://www.bible.com/bible/127/REV.16.NTV' /> se habla de otra señal de los ultimos tiempos dice que se le dara poder para quemar a las persona y realmente ya esta pasando con el sol, por eso dar siempre gracias a Dios por la vida y la salud que nos da diario.
      </Card>
      
      <Card title='Amar al projimo' >
        Demos en todo tiempo su amor, su palabra dice, venir los que estan cansados y el nos hara descansar <Link text='Mateo 11:28' src='https://www.bible.com/bible/127/MAT.11.NTV' /> Cambia tu mala actitud, pidele un cambio a el. <br /> En <Link text='Deuteronomio 6:5' src='https://www.bible.com/bible/127/DEU.6.NTV' /> nos dice como amar, tambien como es importante amar a Dios asi mismo a tu projimo. <br /> Ser tolerantes como Jesus, el recibio tantos insultos y ni siquiera abrio su boca dice la biblia. <br /> Demuestra tu amor y el amor de tu padre celestial con tu actitud, con tu generosidad y compartiendo su palabra. <br /> Porque no perdonar, porque no ser tolerantes si el lo es con nosotros. <Link text='Lucas 10:25--' src='https://www.bible.com/bible/127/LUK.10.NTV' /> Ama eso te dara la heredady ayuda a tu projimo, no ser egoista, no ser enojado, ten una sonrisa, reflejar a Dios un feliz y contento corazon. Tener una buena conducta, ser amables pedir la gracia, recibir la correccion es de sabios.
      </Card>
      
      <Card title='Muchos son los llamados pero pocos los escogidos' >
        <Subt sub='Los atributos de un escogido'/> <Link text='2 Cronicas 26:1' src='https://www.bible.com/bible/127/2CH.26.NTV' /> El rey Uzias (significa Dios es mi fuerza) este rey es un escogido Aunque tener cuidado aunque seamos escogidos incluso Samuel habia sido engaño cuando fue a ungir a David es habia confundido y ahi podemos ver que solo uno fue un escogido y 7 llamados y aqui podemos aprender que Dios le enseño que no se fijara en lo de afuera si no lo de adentro. <br /> El rey Uzias uno de sus atributos es que era temeroso de Dios y Dios no se aparto de el mientras fue recto. <br /> Un ejemplo esta <Link text='1 Reyes 1:1--' src='https://www.bible.com/bible/127/1KI.1.NTV' /> aqui podemos ver que escogieron a una hermosa mujer y realmente escoger no es facil. <br /><Link text='2 Cronicas 26:4-5' src='https://www.bible.com/bible/149/2CH.26.RVR1960' /> en el 5 dice que persistio, percebero, insistio en buscar a Dios, "Persiste y alcanzaras" no te des por vencido el atributo Perceberante, no pares de persiste, <Link text='Santiago 5:17' src='https://www.bible.com/bible/127/JAS.5.NTV' /> aqui nos muestra otro atributo, orar con fervor, Elias oraba creyendo que Dios lo cumpliria y recuerden sin fe es imposible agradar a Dios. <br /> Persistir tambien significa cuidarse. <br /> En <Link text='2 Cronicas 26:5' src='https://www.bible.com/bible/149/2CH.26.RVR1960' /> aqui dice que en los tiempos de Zacarias, pero no ser como el que veia a su mentor si no nosotros ver al Dios que es eterno. <br /> Y por ultimo no rendirnos la recompensa es grande pelea la buena batalla de la fe <Link text='1 Timoteo 6:12' src='https://www.bible.com/bible/127/1TI.6.NTV' />
      </Card>

      <Card title='Gran yo soy' >
        El Dios altisimo cada uno tenemos un don diferente, nos usa de diferentes maneras, el ve nuestras cualidades el nos examina como lo hizo con Moises el vio que era capaz de hacerlo <Link text='Exodo 3:13' src='https://www.bible.com/bible/127/EXO.3.NTV' /> Pero aqui podemos ver al mas adelante en el 14, Jehova le dice que el es el que es, él es el todo, el da la vida y el la quita <Link text='Deuteronomio 32:39' src='https://www.bible.com/bible/127/DEU.32.NTV' /> <br /> El es el que nos respalda, no temas que el esta con nosotros y el es el gran yo soy el es nuestro Dios altisimo asi que porque temer? el pelea nuestra batalla el esta en todo momento con nostros, el tiene el poder un gran poder como el que dice en <Link text='Juan 10:17-18' src='https://www.bible.com/bible/127/JHN.10.NTV' /> <br /> El penso cada pequeña cosa de nostros, dicen que incluso antes de venir a este mundo Dios ya nos tenia pensados, el nos hizo unicos, especiales todo ese cuidado lo tuvo mi Dios celestial. <br /> Como dice en <Link text='Nehemias 9:6' src='https://www.bible.com/bible/127/NEH.9.NTV' /> Solo tu eres el señor mi Dios eterno. <br /> Otro hermoso versiculo es <Link text='Isaias 44:1-2' src='https://www.bible.com/bible/127/ISA.44.NTV' /> el nos eligio no tengamos miedo que el estara. <br /> El tuvo el control de cada cosa de nosotros el conoce el numero de nuestros cabellos, el tuvo el control de nuestra estatura, color de piel, cada detalle de nuestros cuerpos como lo dice en <Link text='Salmos 139:13' src='https://www.bible.com/bible/127/PSA.139.NTV' /> el tuvo el cuidado hasta de nuestros padre y por ultimo el tambien tenia el cuidado de nuestra ciudadania celestial, <Link text='Santiago 1:18' src='https://www.bible.com/bible/127/JAS.1.NTV' />
      </Card>

      <Card title='Un dia despues de la muerte'>
        <Link text='Eclesiastes 8:8' src='https://www.bible.com/bible/127/ECC.8.NTV' /> No podemos librarnos de ese dia, solo Dios tiene el control <br /> Las personas entran en un gran desanimo, los que se quedan sufren <br /> No afarnarnos por las cosas que dejan <br /> Portarnos bien para no tener remordimiento <br /> Lo que tienes comelo, disfrutalo, no nos llevamos nada y solo lo dejamos para pleitos <Link text='Eclesiastes 3:13' src='https://www.bible.com/bible/127/ECC.3.NTV' /> goza de lo que tienes <br /> Algun dia solo seremos un recuedo, asi que tratar de ser uno bueno por lo menos. <br /> Recuerda que tu diploma no les dara de comer a las personas que se quedan asi que mejor ve y haz lindos recuerdos no te afanes con el conocimiento procura disfrutar mas tu vida <br /> No guardes tu cuerpo este cuerpo no es eterno, mejor busca de Dios, mejor cuida tu alma <br /> Nos comparan como animales <Link text='Salmos 32:9' src='https://www.bible.com/bible/127/PSA.32.NTV' />  <Link text='Isaias 1:3' src='https://www.bible.com/bible/127/ISA.1.NTV' /> que somos pues para reverlarnos o decirle algo al padre. <br /> Los años se estan acabando, que hemos hecho por el señor? hemos ganado un galardon? hemos dado a luz a una ovejita? recuerda que la esterilidad es una vergüenza  <Link text='Lucas 1:25' src='https://www.bible.com/bible/127/LUK.1.NTV' /> <br /> Que beneficio tiene tu vida, es lindo cuando llevas a una alma a los pies de Dios, quitemonos esa vergüenza, recordemos los galardones que recibiremos, ora por esas ovejas. <br /> Recuerda que este cuerpo es una carcel y que la muerte es una ganacia. <Link text='Filipenses 1:21' src='https://www.bible.com/bible/149/PHP.1.RVR1960' />
      </Card>

      <Card title='Un segundo despues de la muerte' >
        En un abrir y cerrar de ojos sonara la trompeta y toda oportunidad terminar, por eso nos venimos preparanado dia con dia, podemos vivir la vida como queramos pero todos nos presentaremos ante Dio el nos dio la libertad de escoger bien o mal. <br /> Nosotros mismos acortamos la vida, <Link text='Nehemias 9:6' src='https://www.bible.com/bible/127/NEH.9.NTV' /> Tu solo tu Dios <br /><Link text='Isaias 44:1' src='https://www.bible.com/bible/127/ISA.44.NTV' /> El nos eligio, el nombre, todo el lo eligio, entonces no maldecir a tus padres o a otra cosa por tus condiciones por tu pobreza o algo asi. <br /> El olvido tu pecadopero arrepientete <Link text='Hechos 17:30' src='https://www.bible.com/bible/127/ACT.17.NTV' /> El vino a perdonar pero nos demanda que ya no pequemos mas. <br /> Muestra al mundo nuestra transformacion, por medio del testimonio <Link text='1 Juan 3:1' src='https://www.bible.com/bible/127/1JN.3.NTV' /> No solo fuimos llamados para ser hijios de Dios tambien para cumplir su proposito. <br /> El primer compromiso a sido con Dios como el matrimonio. <Link text='Efesios 1:3-5' src='https://www.bible.com/bible/127/EPH.1.NTV' /> Antes de la creacion del mundo el nos habia escogido y nos amo, todos tenemos un plan divino de Dios, el nos da el perdon y hasta una herencia <Link text='1 Pedro 1:3-12' src='https://www.bible.com/bible/127/1PE.1.NTV' /> y aparte de la herencia el promete que estara con nosotros, dijo que donde Jesus esta el quiere que nosotros estemos y Jesus esta a la diestra del Padre. En aquel dia lo veremos cara a cara al segundo, asi que pelea la buena batalla. <br /> <Link text='Marcos 8:34-35' src='https://www.bible.com/bible/127/MRK.8.NTV' /> Pertenecemos a su familia, beneficios de ser su familia <Link text='Filipenses 4:19' src='https://www.bible.com/bible/127/MRK.8.NTV' /> <br /> Somos de Dios <Link text='Juan 17:10' src='https://www.bible.com/bible/127/JHN.17.NTV' /> <br /> No hablar si somos hijos de Dios <Link text='Lucas 15:31' src='https://www.bible.com/bible/127/LUK.15.NTV' />
      </Card>

      <Card title='Pruebas ultimo tiempo' >
        Recordemos que el tienen pensamientos de bien y no de mal, una comunion es igual a union, relacion, estar entrelasados. Dios quiere hablar pero primero debemos callar <Link text='Zacarias 2:13' src='https://www.bible.com/bible/127/ZEC.2.NTV' /> El nos protege <Link text='Zacarias 9:15' src='https://www.bible.com/bible/127/ZEC.9.NTV' /> <br /> <Link text='Zacarias 13:1' src='https://www.bible.com/bible/127/ZEC.13.NTV' /> ese manantial de purificacion es igual a Jesus. Viene algo sobre la tierra <Link text='Zacarias 12:1-2' src='https://www.bible.com/bible/127/ZEC.12.NTV' /> Israel es el reloj es nuestra señal asi que es importante poner los ojos en su pueblo santo. Palestino = filisteos. El problema para los demas es Israel ya que es la tierra del gran rey <Link text='Zacarias 8:3' src='https://www.bible.com/bible/127/ZEC.8.NTV' /> <br /> <Link text='Zacarias 7:12' src='https://www.bible.com/bible/127/ZEC.7.NTV' /> hemos endurecido nuestro corazones como todos unos tercos. Jeremias = Dios pone orden, <Link text='Jeremias 6:16' src='https://www.bible.com/bible/127/JER.6.NTV' /> para no sigas y vuelve al camino. <br /> Tener fervor, orar fervientemente con sentimiento, persistir, una llave para que nos escuche es orar con actitud orar con la conviccion que ya nos ha escuchado y el cumplira todo nos falta busqueda. Antes ni siquiera se atrevian a acercarles <Link text='Hechos 5:12-15' src='https://www.bible.com/bible/127/ACT.5.NTV' /> <br /> Que esta pasando, necesitamos que se manifieste, no hay que desanimarnos. Por favor no te quedes <Link text='Daniel 8:23' src='https://www.bible.com/bible/127/DAN.8.NTV' /> lo que viene no es bueno por eso para, analiza y vuelve al camino, pelea la buena batalla si estamos perdidos ser sinceros aceptarlo y decirle el siempre te estara esperando.
      </Card>
    </div>
    
  );
}

export default App;
